resources:
  genome: 'hg19/hg19_refgene/hg19.fa'
  gtf: 'hg19/hg19_refgene/hg19.refGene.gtf'
  bwa_index: 'hg19/hg19_bwa_index/hg19'
  fq_dir: 'fastq/'
  fq1: '{sample}.fastq'
  fq2: '{sample}.fastq'
  RG: "@RG\\tID:{sample}_SE\\tSM:{sample}\\tPL:Illumina"
  bwa_map: 'bwa_mapped_reads/{sample}.bam'
  picard_clean: 'picard/{sample}.clean.bam'
  picard_mkdup_bam: 'picard/{sample}.mkdup.bam'
  picard_mkdup_txt: 'picard/{sample}.mkdup.txt'

snakefile: all_rules.smk
cores: 6
latency-wait: 60
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 3
